In [26]:
from __future__ import division
from __future__ import print_function
import numpy as np

In [27]:
# X = np.array([[1,-0.5,0.2],[1,0.5,1.5],[1,2,1.7]])
# Y = np.array([-1,1,-1])
# W = np.array([1,1,1])

X = np.array([[1,-0.5,0.2],[1,0.5,1.5],[1,2,1.7]])
Y = np.array([-1,1,-1])
W = np.array([1,1,1])

In [28]:
# Q4

for row in np.arange(len(X)):
    print ()
    x = X[row,:]
    y = Y[row]
    WTX = np.dot(x,W.T)
#     print (WTX)
#     print (W + (x*y))
    if WTX*y <= 0:
#         print (W)
#         print ((x*y))
        W = W + (x*y)
    print (W)
    
print (W)


[ 0.   1.5  0.8]

[ 0.   1.5  0.8]

[-1.  -0.5 -0.9]
[-1.  -0.5 -0.9]
