In [3]:
# Import all the relevant libraries.
import nltk
import itertools
import numpy as np
import csv
import tensorflow as tf
import tempfile

In [46]:
sequences = [[1, 2, 3], [4, 5, 1], [1, 2]]
label_sequences = [[0, 1, 0], [1, 0, 0], [1, 1]]

def make_example(sequence, labels):
    # The object we return
    ex = tf.train.SequenceExample()
    # A non-sequential feature of our example
    sequence_length = len(sequence)
    ex.context.feature["length"].int64_list.value.append(sequence_length)
    # Feature lists for the two sequential features of our example
    fl_tokens = ex.feature_lists.feature_list["tokens"]
    fl_labels = ex.feature_lists.feature_list["labels"]
    for token, label in zip(sequence, labels):
        fl_tokens.feature.add().int64_list.value.append(token)
        fl_labels.feature.add().int64_list.value.append(label)
    return ex

# Write all examples into a TFRecords file
with tempfile.NamedTemporaryFile(delete=False) as fp:
    print (fp.name)
    writer = tf.python_io.TFRecordWriter(fp.name)
    for sequence, label_sequence in zip(sequences, label_sequences):
        print ('brbrbrbrbrbr')
        print (sequence, label_sequence)
        ex = make_example(sequence, label_sequence)
        print (ex)
        writer.write(ex.SerializeToString())
    writer.close()
    print("Wrote to {}".format(fp.name))

/var/folders/5w/xz07kq3x5zvdn0s8dk24tdm00000gn/T/tmpx0cgxv93
brbrbrbrbrbr
[1, 2, 3] [0, 1, 0]
context {
  feature {
    key: "length"
    value {
      int64_list {
        value: 3
      }
    }
  }
}
feature_lists {
  feature_list {
    key: "labels"
    value {
      feature {
        int64_list {
          value: 0
        }
      }
      feature {
        int64_list {
          value: 1
        }
      }
      feature {
        int64_list {
          value: 0
        }
      }
    }
  }
  feature_list {
    key: "tokens"
    value {
      feature {
        int64_list {
          value: 1
        }
      }
      feature {
        int64_list {
          value: 2
        }
      }
      feature {
        int64_list {
          value: 3
        }
      }
    }
  }
}

brbrbrbrbrbr
[4, 5, 1] [1, 0, 0]
context {
  feature {
    key: "length"
    value {
      int64_list {
        value: 3
      }
    }
  }
}
feature_lists {
  feature_list {
    key: "labels"
    value {
      feature {
 

In [43]:
ex = make_example([1, 2, 3], [0, 1, 0]).SerializeToString()
print (ex)

b'\n\x11\n\x0f\n\x06length\x12\x05\x1a\x03\n\x01\x03\x12B\n\x1f\n\x06tokens\x12\x15\n\x05\x1a\x03\n\x01\x01\n\x05\x1a\x03\n\x01\x02\n\x05\x1a\x03\n\x01\x03\n\x1f\n\x06labels\x12\x15\n\x05\x1a\x03\n\x01\x00\n\x05\x1a\x03\n\x01\x01\n\x05\x1a\x03\n\x01\x00'


In [1]:
import nltk
import itertools
import numpy as np
import csv
import tensorflow as tf
import tempfile

# Create input data
X = np.random.randn(2, 10, 8)
#print (X)

# The second example is of length 6 
X[1,6:] = 0
X_lengths = [10, 6]
#print (X) 
cell = tf.nn.rnn_cell.LSTMCell(num_units=64, state_is_tuple=True)

print (X_lengths)

outputs, last_states = tf.nn.dynamic_rnn(
    cell=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)
print (outputs)
print (last_states)

result = tf.contrib.learn.run_n(
    {"outputs": outputs, "last_states": last_states},
    n=1,
    feed_dict=None)

print (result[0]['outputs'])
print ('')
print (result[0]['last_states'])

print ('')
print (result[0]['outputs'].shape)
print ('')
print (result[0]['last_states'].shape)
# assert result[0]["outputs"].shape == (2, 10, 64)
 
# # Outputs for the second example past past length 6 should be 0
# assert (result[0]["outputs"][1,7,:] == np.zeros(cell.output_size)).all()

[10, 6]
Tensor("RNN/transpose:0", shape=(2, 10, 64), dtype=float64)
LSTMStateTuple(c=<tf.Tensor 'RNN/while/Exit_2:0' shape=(?, 64) dtype=float64>, h=<tf.Tensor 'RNN/while/Exit_3:0' shape=(?, 64) dtype=float64>)
[[[-0.04873879  0.10236598  0.0021114  ..., -0.06977061 -0.00206842
   -0.046741  ]
  [-0.01891798 -0.00677315  0.0438622  ..., -0.08005247 -0.02644221
   -0.0076705 ]
  [-0.09608614 -0.00132416  0.07090155 ..., -0.1006073   0.10859604
   -0.12559532]
  ..., 
  [-0.13227843  0.04518689  0.06229541 ..., -0.00873055 -0.10966313
   -0.13659457]
  [-0.08084598  0.13268095  0.0869037  ..., -0.23884922 -0.12731657
   -0.07712269]
  [-0.09825347  0.12436559  0.09828475 ..., -0.29004013 -0.1091157
   -0.03407121]]

 [[ 0.04929381 -0.0422543   0.12561429 ..., -0.14302551 -0.00308286
    0.07752118]
  [ 0.08865711  0.04189393  0.1380182  ..., -0.15630243  0.13257326
    0.03757834]
  [-0.00509037  0.07774722  0.11640103 ..., -0.03791107  0.13381177
   -0.06342925]
  ..., 
  [ 0.          

AttributeError: 'LSTMStateTuple' object has no attribute 'shape'

In [2]:
X = np.random.randn(2, 10, 8)
X[1,6:] = 0
X_lengths = [10, 6]
print (X)

[[[ 0.71729017  0.38172224 -0.19956801  0.18194343  0.4226487   1.26298561
    0.26444865  1.14601832]
  [-1.69835228  0.36769151 -0.97402884 -0.22190664 -1.32952568  1.90069161
   -0.73010785  2.58890676]
  [-0.29910887  1.0506534   1.2457377   0.7183096  -1.09795046  0.22264103
    0.80217631  1.13985377]
  [-1.49979326  0.10177676  1.03760234 -0.26978718  0.11370536 -0.13927117
    0.67128343  0.37829628]
  [-0.66523676  0.3780318  -1.60910249  0.34122314 -0.3043356   0.48667331
    1.77451634 -0.15910965]
  [-0.20552565  0.89049555 -0.83274045  0.92981967  0.0352854   0.45086225
    0.89434934  0.64517888]
  [ 0.56322204  2.08886899  0.90857296 -0.1386985   0.08930235  1.80820731
   -0.42374246  0.26622877]
  [ 1.32100964  1.22270941  0.4910494   0.42273964 -0.29738031  0.50211067
    0.94574481  1.20778073]
  [ 0.48940962 -0.35273309 -0.62539853 -0.53045273  0.0611717  -0.53763615
    0.98887272 -1.6986863 ]
  [-0.74387118  0.58016334 -1.43500145  0.34712719  0.88307306  0.1515889

In [4]:
cell = tf.nn.rnn_cell.LSTMCell(num_units=64, state_is_tuple=True)
outputs, last_states = tf.nn.dynamic_rnn(
    cell=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)

In [5]:
result = tf.contrib.learn.run_n(
    {"outputs": outputs, "last_states": last_states},
    n=1,
    feed_dict=None)

In [6]:
assert result[0]["outputs"].shape == (2, 10, 64)
 
# Outputs for the second example past past length 6 should be 0
assert (result[0]["outputs"][1,7,:] == np.zeros(cell.output_size)).all()

In [11]:
# Batch size
B = 4
# (Maximum) number of time steps in this batch
T = 8
RNN_DIM = 128
NUM_CLASSES = 10
 
# The *acutal* length of the examples
example_len = [1, 2, 3, 8]

In [13]:
y = np.random.randint(1, 10, [B, T])
# print (y)
for i, length in enumerate(example_len):
    y[i, length:] = 0
print (y)

[[7 0 0 0 0 0 0 0]
 [7 5 0 0 0 0 0 0]
 [1 4 6 0 0 0 0 0]
 [3 2 7 2 6 3 6 1]]


In [10]:
print (np.random.randn(B, T, RNN_DIM))
rnn_outputs = tf.convert_to_tensor(np.random.randn(B, T, RNN_DIM), dtype=tf.float32)

[[[ 1.24816858 -1.02868492 -0.32723761 ...,  0.89143523  1.29687748
    1.41751645]
  [ 0.78750023  0.07460371  0.62385024 ..., -0.05200256 -0.79829592
    0.05485426]
  [ 1.62101833 -0.33461718 -0.04583753 ...,  0.5211199  -1.63472385
   -0.53852207]
  ..., 
  [ 0.15       -1.92283121  0.50407152 ...,  1.0857052   0.40723821
   -0.0592604 ]
  [-1.22547093  1.06354622  1.14514789 ..., -0.82929861 -0.70123027
    0.35377178]
  [ 1.37172679  0.62591802  0.12420518 ..., -0.40507739  1.06380225
    0.83426676]]

 [[ 1.24284251 -0.74996992 -0.87424085 ..., -1.12416666 -0.37375604
   -0.41404776]
  [-0.42914737  1.01445022  0.66648177 ..., -0.33892189 -0.97711094
    0.71569148]
  [ 2.3953511  -0.06444704  0.53516596 ...,  0.5042704  -0.45069737
    0.6900618 ]
  ..., 
  [-0.31629941  1.13576453 -0.282383   ...,  1.10215908 -0.86170042
   -0.81889879]
  [-0.77989527  0.28624587  1.1382271  ...,  0.7663907  -0.77374105
   -0.00796684]
  [ 1.29787243 -0.43243785  0.5627917  ..., -0.21650726  0

In [14]:
W = tf.get_variable(
    name="W",
    initializer=tf.random_normal_initializer(),
    shape=[RNN_DIM, NUM_CLASSES])
 



In [4]:
# From here we start the output 

# first we define a X
X = np.random.randn(2, 10, 8)
X[1,6:] = 0
print (X)

# Define the lenght of the X, this will be used by the model to specify how much is the sequence length for every 
# row data in the batch.
X_lengths = [10, 6]  # the length of the first row is 10 and the second is 6

[[[  8.31628272e-01  -9.51258190e-01  -1.04584514e+00   8.49072735e-01
    -1.48134684e+00   2.57791010e-01  -5.34378495e-01  -2.35166282e-01]
  [  2.90960523e-01  -1.82827690e+00  -1.71681322e-02   5.76078651e-01
    -1.07068828e+00  -3.96379153e-02   7.94747875e-01   9.80964214e-02]
  [  1.04343754e+00  -7.82537709e-01   1.55866738e+00  -1.53077798e-01
     5.87398368e-01  -3.94689237e-01  -5.31558823e-01  -2.60934876e-02]
  [  1.01955015e+00  -1.29134367e+00   1.87678729e-01   9.43079541e-01
     1.54198861e+00  -1.55184666e-01   3.25353825e-01  -1.90262942e-01]
  [  3.20225521e-01  -8.81380227e-01  -8.61900314e-01  -8.52258155e-01
     2.73513882e-01   6.67043804e-01   1.19761469e+00   4.83434182e-01]
  [  2.11721673e-03  -5.74893415e-02  -7.35234707e-01   2.60533348e-01
     1.73545180e-01  -1.18199060e+00   1.95716322e+00  -1.50267564e-01]
  [  5.90561765e-01  -4.50174188e-01  -1.04528783e+00   1.00861189e+00
    -7.60281574e-01   6.98109033e-02  -1.14628515e+00   4.68023206e-01]

In [5]:
# Model :
# Define the type of optimization we need:
cell = tf.nn.rnn_cell.LSTMCell(num_units=64, state_is_tuple=True) # Here we choose LSTM
# We then wrap the abobe objects with a RNN wrapper with dynamic
outputs, last_states = tf.nn.dynamic_rnn(
    cell=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)

In [6]:
# Define the variable where to store the result:
result = tf.contrib.learn.run_n(
    {"outputs": outputs, "last_states": last_states},
    n=1,
    feed_dict=None)

In [9]:
assert result[0]["outputs"].shape == (2, 10, 64)   # The shape is 2, 10, 64 
# where 2 indicates the number of batches
# 10 indicates the number of classes