In [1]:
from __future__ import division
 
import numpy as np

#### Question 2.1 - (i) page(84): 

In [27]:
A = np.array([[1,1,1,1], [1,-1,-1,1],[0,1,0,1]])

B = A[:,[0,1,3]]
N = A[:,[2]]

print ('B: ', B)

B_inv = np.linalg.inv(B)

Z = -1 * np.dot(B_inv, N)

Z = Z.flatten()
Z = np.append(Z, 1)
Z = Z.reshape(4,1)

print ('Z: ', Z)
isZero = np.dot(A, Z)
print ('isZeros: ', isZero)




B:  [[ 1  1  1]
 [ 1 -1  1]
 [ 0  1  1]]
Z:  [[-1.]
 [-1.]
 [ 1.]
 [ 1.]]
isZeros:  [[ 0.]
 [ 0.]
 [ 0.]]


In [34]:
A = np.array([[1,1,0,-1],[1,-1,1,-1],[1,-1,0,1],[1,1,1,1]])
b1 = np.array([1,3,1,2])
b2 = np.array([0,-2,-3,4])
np.linalg.solve(A,b2)

array([-1.5 ,  2.25,  2.5 ,  0.75])

#### Question 2.1 - (ii) page(84): 

In [37]:
A = np.array([[1,1,1,1]])

B = A[:,[0]]
N = A[:,[1,2,3]]

print ('B: ', B)

B_inv = np.linalg.inv(B)

print ('B_INV: ', B_inv)

Z = -1 * np.dot(B_inv, N)

Z = Z.flatten()
Z = np.append(Z, 1)
Z = Z.reshape(4,1)

print ('Z: ', Z)
isZero = np.dot(A, Z)
print ('isZeros: ', isZero)




B:  [[1]]
B_INV:  [[ 1.]]
Z:  [[-1.]
 [-1.]
 [-1.]
 [ 1.]]
isZeros:  [[-2.]]


In [40]:
A = np.array([[1,-1,-1,-1],
              [1,1,0,0],
              [1,0,1,0],
              [1,0,0,1]])
b1 = np.array([7,5,-13,1])
# b2 = np.array([0,-2,-3,4])
np.linalg.solve(A,b1)

array([  0.,   5., -13.,   1.])

### Question 2.1, Page:481

In [67]:
import numpy as np
import sympy as sp

x1 = sp.Symbol('x1')
x2 = sp.Symbol('x2')
x3 = sp.Symbol('x3')
fx = pow(x1,2) + pow(x1,2)*pow(x3,2) + 2*x1*x2 + pow(x2,4) + 8*x2
constraint = [2*x1 + 5*x2 + x3]

deriv1 = np.array([fx.diff(inp) for inp in [x1,x2,x3]]).reshape(3,1)
deriv2 = np.array([order1.diff(diff_wrt) 
                   for order1 in deriv1.flatten() 
                   for diff_wrt in [x1,x2,x3]]).reshape(3,3)

print (deriv1)
A = [2,5,1]
b = 3
B = 2
N = np.array([5,1])
Z = np.array([-1*(1/B)*N])
Z = np.vstack((Z, [1,0], [0,1]))
print (Z)
# Check if the first order derivative is 0. To show the 1st order derivative is 0 we substitute
# different values of [x1,x2,x3] into deriv1 and perform np.dot(Z.T, deriv1)
X_arr = np.array([[0,0,2], [0,0,3], [1,0,1]]) # x1=0, x2=0, x3=2
for X in X_arr:
    print ('')
    print (X)
    deriv1_subs = np.array([fnc.evalf(subs={x1:X[0], x2:X[1], x3:X[2]}) for fnc in deriv1.flatten()])
    print (deriv1_subs)
    print(np.dot(Z.T,deriv1_subs))

# Check if the second order derivative is positive semi definite


[[2*x1*x3**2 + 2*x1 + 2*x2]
 [2*x1 + 4*x2**3 + 8]
 [2*x1**2*x3]]
[[-2.5 -0.5]
 [ 1.   0. ]
 [ 0.   1. ]]

[0 0 2]
[0.e-125 8.00000000000000 0]
[8.00000000000000 -5.90910631538287e-126]

[0 0 3]
[0.e-125 8.00000000000000 0]
[8.00000000000000 -5.90910631538287e-126]

[1 0 1]
[4.00000000000000 10.0000000000000 2.00000000000000]
[0 0]


In [76]:
# Show if the stationary point [1,0,1] is minimizer, maximizer or saddle point
X_arr = np.array([[1,0,1]]) # x1=0, x2=0, x3=2
for X in X_arr:
    print ('')
    print (X)
    XCopy = X
    print (XCopy)
    deriv1_subs1 = np.array([fnc.evalf(subs={x1:XCopy[0], x2:XCopy[1], x3:XCopy[2]}) for fnc in deriv1.flatten()])
    print (deriv1_subs1)
    print(np.dot(Z.T,deriv1_subs1))
    print ('')
    
    XCopy = X+0.01
    print (XCopy)
    deriv1_subs2 = np.array([fnc.evalf(subs={x1:XCopy[0], x2:XCopy[1], x3:XCopy[2]}) for fnc in deriv1.flatten()])
    print (deriv1_subs2)
    print(np.dot(Z.T,deriv1_subs2))
    print('')
    
    XCopy = np.array([X[0]-0.01, X[1]+0.01, X[2]+0.01])
    print (XCopy)
    deriv1_subs3 = np.array([fnc.evalf(subs={x1:XCopy[0], x2:XCopy[1], x3:XCopy[2]}) for fnc in deriv1.flatten()])
    print (deriv1_subs3)
    print(np.dot(Z.T,deriv1_subs3))
#     print(np.dot(Z.T,deriv1_subs))


[1 0 1]
[1 0 1]
[4.00000000000000 10.0000000000000 2.00000000000000]
[0 0]

[ 1.01  0.01  1.01]
[4.10060200000000 10.0200040000000 2.06060200000000]
[-0.231501000000002 0.0103010000000001]

[ 0.99  0.01  1.01]
[4.01979800000000 9.98000400000000 1.97980200000000]
[-0.0694910000000011 -0.0300969999999998]


In [58]:
# Finding the solution:

eq1 = np.dot(Z.T,deriv1)
eq2 = np.array([constraint])
eq = np.vstack((eq1, eq2))

print(eq)
print('')


from sympy.solvers import solve
# Solving the system of equation Ax = b where b=[0,0,3]
b_extended = np.array([0,0,3]) # 0's corresponds to eq1 and 3 corresponds to eq2
e1 = -5.0*x1*x3**2 - 3.0*x1 + 4.0*x2**3 - 5.0*x2 + 8.0 - b_extended[0]
e2 = 2.0*x1**2*x3 - 1.0*x1*x3**2 - 1.0*x1 - 1.0*x2 - b_extended[1]
e3 = 2*x1 + 5*x2 + x3 - b_extended[2]
print('solution x1,x2,x3 are: ', solve([e1,e2,e3],(x1,x2,x3)))
print('')


[[-5.0*x1*x3**2 - 3.0*x1 + 4.0*x2**3 - 5.0*x2 + 8.0]
 [2.0*x1**2*x3 - 1.0*x1*x3**2 - 1.0*x1 - 1.0*x2]
 [2*x1 + 5*x2 + x3]]

solution x1,x2,x3 are:  [(1.00000000000000, 0.0, 1.00000000000000)]

