In [1]:
from __future__ import division
 
import numpy as np

#### Question 2.1 - (i) page(84): 

In [27]:
A = np.array([[1,1,1,1], [1,-1,-1,1],[0,1,0,1]])

B = A[:,[0,1,3]]
N = A[:,[2]]

print ('B: ', B)

B_inv = np.linalg.inv(B)

Z = -1 * np.dot(B_inv, N)

Z = Z.flatten()
Z = np.append(Z, 1)
Z = Z.reshape(4,1)

print ('Z: ', Z)
isZero = np.dot(A, Z)
print ('isZeros: ', isZero)




B:  [[ 1  1  1]
 [ 1 -1  1]
 [ 0  1  1]]
Z:  [[-1.]
 [-1.]
 [ 1.]
 [ 1.]]
isZeros:  [[ 0.]
 [ 0.]
 [ 0.]]


In [34]:
A = np.array([[1,1,0,-1],[1,-1,1,-1],[1,-1,0,1],[1,1,1,1]])
b1 = np.array([1,3,1,2])
b2 = np.array([0,-2,-3,4])
np.linalg.solve(A,b2)

array([-1.5 ,  2.25,  2.5 ,  0.75])

#### Question 2.1 - (ii) page(84): 

In [37]:
A = np.array([[1,1,1,1]])

B = A[:,[0]]
N = A[:,[1,2,3]]

print ('B: ', B)

B_inv = np.linalg.inv(B)

print ('B_INV: ', B_inv)

Z = -1 * np.dot(B_inv, N)

Z = Z.flatten()
Z = np.append(Z, 1)
Z = Z.reshape(4,1)

print ('Z: ', Z)
isZero = np.dot(A, Z)
print ('isZeros: ', isZero)




B:  [[1]]
B_INV:  [[ 1.]]
Z:  [[-1.]
 [-1.]
 [-1.]
 [ 1.]]
isZeros:  [[-2.]]


In [40]:
A = np.array([[1,-1,-1,-1],
              [1,1,0,0],
              [1,0,1,0],
              [1,0,0,1]])
b1 = np.array([7,5,-13,1])
# b2 = np.array([0,-2,-3,4])
np.linalg.solve(A,b1)

array([  0.,   5., -13.,   1.])