In [1]:
from __future__ import division
import numpy as np

### Linear Programming/Optimization: Finding the global optimum searching the entire basic solution space:

In [11]:
BB = np.array([[2,1,0,0,1],
               [1,1,0,1,0],
               [1,0,1,0,0]])

B = BB[:,[0,3,4]]
b = np.array([[100],[80],[40]])

np.dot(np.linalg.inv(B), b)

array([[ 40.],
       [ 40.],
       [ 20.]])

In [24]:
BB = np.array([[-3,2,1,0],
               [-2,1,0,1]])

B = BB[:,[2,3]]
b = np.array([[30],[12]])

np.dot(np.linalg.inv(B), b)

array([[ 30.],
       [ 12.]])

In [17]:
BB = np.array([[0,2,(30/11)],
               [4,0,(4/11)],
               [1,1,1]])

CC = np.array([[2,3,(30/11)],
               [0,0,(4/11)],
               [1,1,1]])

In [19]:
np.dot(np.linalg.inv(CC), np.array([[1],[1],[1]]))

array([[ 1.25],
       [-3.  ],
       [ 2.75]])

### Linear Programming/Optimization: Iteration through basic solution while minimizing:

In [76]:
A = np.array([[2,1,1,0], [1,4,0,1]])  # The input matrix in standard form
b = np.array([3,4]) # The response variables
C = np.array([-7,-6,0,0]).reshape(1,4) # The function to minimize
X = np.array(['x'+str(i) for i in np.arange(1,A.shape[1]+1)]).reshape(1,4)
basicVar = [2,3]

print (X)
def linearOptimization(A, b, C, X, basicColIndex):
    i = 0
    X_copy = X
    while i<10:
        Xb = X[:,basicColIndex]
        Xn = X[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        X_copy = np.column_stack((Xb, Xn))
        
        # xVar = []
        B = A[:,basicColIndex]   # chose a square matrix
        N = A[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        Cb = C[:,basicColIndex].flatten()
        Cn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten()
        y = np.dot(np.linalg.inv(B).T, Cb)
        Cn_hat = Cn - np.dot(N.T,y)
        print ('')
        print ('')
        print ('BBBBBBBBBB: \n', B)
        print ('bbbbbbbbbb: \n', b)
        print ('NNNNNNNNNN: \n', N)
        print ('XbXbXbXbXb: \n', Xb)
        print ('XnXnXnXnXn: \n', Xn)
        print ('CbCbCbCbCb = C[:,basicColIndex].flatten(): \n', Cb)
        print ('CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() \n', Cn)
        print ('yyyyyyyyyy: \n', y)
        print ('Cn_hatCn_hat: \n', Cn_hat)
        # Check if all elements in Cn_hat >= 0, if so then, we have our optimal vertex which is B
        
        feasibleSol = np.dot(np.linalg.inv(B), b)
        print ('########################### ',feasibleSol)
        if any(Cn_hat<0):
            print ('Not yet optimal')
        elif min(feasibleSol) < 0:
            print ('Not yet optimal: Since feasible solution is < 0' )
            pass
        else:
            print ('')
            print ('')
            print ('BASIC COLUMNS: ', Xb)
            print ('NULL COLUMNS: ', Xn)

            return feasibleSol

        # Select the most negative value in the array 
        indice = np.where(Cn_hat == Cn_hat.min())[0][0]
        ct_hat = Cn_hat[indice]
        print ('indiceindiceindice: ', indice)
        
        # Get the corresponding at
        at = N[:,indice].reshape(A.shape[0], 1)
        print ('atatatatatatatatatat: ', at)
        b_hat = np.dot(np.linalg.inv(B), b).reshape(A.shape[0], 1)
        print ('b_hatb_hatb_hatb_hat: ', b_hat)
        at_hat = np.dot(np.linalg.inv(B), at)
        print ('at_hatat_hatat_hatat_hat: ', at_hat)
        
        # Find the min epsilon
        b_a = (b_hat/at_hat).flatten()
        print ('b_ab_ab_ab_ab_ab_ab_ab_a: ', b_a)
        indice2 = np.where(b_a == b_a.min())[0][0]
        print ('indice2indice2indice2i: ', indice2)
        epsilon = b_a[indice2]
        print ('epsilonepsilonepsilon: ', epsilon)

        # Vertex points 1 
        vertex1 = b_hat - epsilon*at_hat
        print ('vertex1vertex1vertex1: ', vertex1)
        # Vertex points 2:
        vertex2 = np.zeros(at_hat.shape)
        vertex2[indice2] = epsilon
        print ('ververtex2vertex2vertex2: ', vertex2)

        # New Vertex solution
        xk1_temp = np.vstack((vertex1, vertex2))
        print ('xk1_tempxk1_tempxk1_tempxk1_temp: \n', xk1_temp)
        
        # Now we select the 
        indice3 = np.where(xk1_temp.flatten() != 0)[0]
        print ('indice3indice3: ', indice3)
        print ('X_copyX_copyX_copy: ', X_copy)
        X_new = X_copy.flatten()[indice3]
        print (X_new, X.flatten())
        basicColIndex = np.searchsorted(X.flatten(),X_new)
        
#         xk1_nonzeros = [vals for vals in xk1_temp if vals!=0]#np.zeros(A.shape[1])
#         xk1 = np.zeros(A.shape[1]) 
#         for basic_solution_column in basicColIndex:
#             xk1[basic_solution_column] = xk1_nonzeros[0]
#             xk1_nonzeros = np.delete(xk1_nonzeros, 0)
#         print ('New Basic variable Index are: ', basicColIndex)
#         print ('New Basic solution is: ', xk1)#[:,basic])

        i+=1
    
Cn_hat = linearOptimization(A, b, C, X, basicColIndex=basicVar)
print ('THe solution is: ', Cn_hat)

[['x1' 'x2' 'x3' 'x4']]


BBBBBBBBBB: 
 [[1 0]
 [0 1]]
bbbbbbbbbb: 
 [3 4]
NNNNNNNNNN: 
 [[2 1]
 [1 4]]
XbXbXbXbXb: 
 [['x3' 'x4']]
XnXnXnXnXn: 
 [['x1' 'x2']]
CbCbCbCbCb = C[:,basicColIndex].flatten(): 
 [0 0]
CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() 
 [-7 -6]
yyyyyyyyyy: 
 [ 0.  0.]
Cn_hatCn_hat: 
 [-7. -6.]
###########################  [ 3.  4.]
Not yet optimal
indiceindiceindice:  0
atatatatatatatatatat:  [[2]
 [1]]
b_hatb_hatb_hatb_hat:  [[ 3.]
 [ 4.]]
at_hatat_hatat_hatat_hat:  [[ 2.]
 [ 1.]]
b_ab_ab_ab_ab_ab_ab_ab_a:  [ 1.5  4. ]
indice2indice2indice2i:  0
epsilonepsilonepsilon:  1.5
vertex1vertex1vertex1:  [[ 0. ]
 [ 2.5]]
ververtex2vertex2vertex2:  [[ 1.5]
 [ 0. ]]
xk1_tempxk1_tempxk1_tempxk1_temp: 
 [[ 0. ]
 [ 2.5]
 [ 1.5]
 [ 0. ]]
indice3indice3:  [1 2]
X_copyX_copyX_copy:  [['x3' 'x4' 'x1' 'x2']]
['x4' 'x1'] ['x1' 'x2' 'x3' 'x4']


BBBBBBBBBB: 
 [[0 2]
 [1 1]]
bbbbbbbbbb: 
 [3 4]
NNNNNNNNNN: 
 [[1 1]
 [4 0]]
XbXbXbXbXb: 
 [['x4' '

In [31]:

a = np.array([1,2,3,4])

In [33]:
a = np.delete(a, 0)

In [34]:
a

array([2, 3, 4])

In [110]:
A = np.array([[-2,1,1,0,0], [-1,2,0,1,0], [1,0,0,0,1]])  # The input matrix in standard form
b = np.array([2,7,3]) # The response variables
C = np.array([-1,-2,0,0,0]).reshape(1,A.shape[1]) # The function to minimize
X = np.array(['x'+str(i) for i in np.arange(1,A.shape[1]+1)]).reshape(1,5)
basicVar = [2,3,4]

def linearOptimization(A, b, C, X, basicColIndex):
    i = 0
    X_copy = X
    while i<10:
        Xb = X[:,basicColIndex]
        Xn = X[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        X_copy = np.column_stack((Xb, Xn))
        
        # xVar = []
        B = A[:,basicColIndex]   # chose a square matrix
        N = A[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        Cb = C[:,basicColIndex].flatten()
        Cn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten()
        y = np.dot(np.linalg.inv(B).T, Cb)
        Cn_hat = Cn - np.dot(N.T,y)
        print ('')
        print ('')
        print ('BBBBBBBBBB: \n', B)
        print ('bbbbbbbbbb: \n', b)
        print ('NNNNNNNNNN: \n', N)
        print ('XbXbXbXbXb: \n', Xb)
        print ('XnXnXnXnXn: \n', Xn)
        print ('CbCbCbCbCb = C[:,basicColIndex].flatten(): \n', Cb)
        print ('CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() \n', Cn)
        print ('yyyyyyyyyy: \n', y)
        print ('Cn_hatCn_hat: \n', Cn_hat)
        # Check if all elements in Cn_hat >= 0, if so then, we have our optimal vertex which is B
        
        feasibleSol = np.dot(np.linalg.inv(B), b)
        print ('########################### ',feasibleSol)
        if any(Cn_hat<0):
            print ('Not yet optimal')
        elif min(feasibleSol) < 0:
            print ('Not yet optimal: Since feasible solution is < 0' )
            pass
        else:
            print ('')
            print ('')
            print ('BASIC COLUMNS: ', Xb)
            print ('NULL COLUMNS: ', Xn)

            return feasibleSol

        # Select the most negative value in the array 
        indice = np.where(Cn_hat == Cn_hat.min())[0][0]
        ct_hat = Cn_hat[indice]
        print ('indiceindiceindice: ', indice)
        
        # Get the corresponding at
        at = N[:,indice].reshape(A.shape[0], 1)
        print ('atatatatatatatatatat: ', at)
        b_hat = np.dot(np.linalg.inv(B), b).reshape(A.shape[0], 1)
        print ('b_hatb_hatb_hatb_hat: ', b_hat)
        at_hat = np.dot(np.linalg.inv(B), at)
        print ('at_hatat_hatat_hatat_hat: ', at_hat)
        
        # Find the min epsilon
        b_a = (b_hat/at_hat).flatten()
        print ('b_ab_ab_ab_ab_ab_ab_ab_a: ', b_a)
        indice2 = np.where(b_a == b_a.min())[0][0]
        print ('indice2indice2indice2i: ', indice2)
        epsilon = b_a[indice]
        print ('epsilonepsilonepsilon: ', epsilon)

        # Vertex points 1 
        vertex1 = b_hat - epsilon*at_hat
        print ('vertex1vertex1vertex1: ', vertex1)
        # Vertex points 2:
        vertex2 = np.zeros(at_hat.shape)
        vertex2[indice] = epsilon
        print ('ververtex2vertex2vertex2: ', vertex2)

        # New Vertex solution
        xk1_temp = np.vstack((vertex1, vertex2))
        print ('xk1_tempxk1_tempxk1_tempxk1_temp: \n', xk1_temp)
        
        # Now we select the 
        indice3 = np.where(xk1_temp.flatten() != 0)[0]
        print ('indice3indice3: ', indice3)
        print ('X_copyX_copyX_copy: ', X_copy)
        X_new = X_copy.flatten()[indice3]
        print (X_new, X.flatten())
        basicColIndex = np.searchsorted(X.flatten(),X_new)
        
#         xk1_nonzeros = [vals for vals in xk1_temp if vals!=0]#np.zeros(A.shape[1])
#         xk1 = np.zeros(A.shape[1]) 
#         for basic_solution_column in basicColIndex:
#             xk1[basic_solution_column] = xk1_nonzeros[0]
#             xk1_nonzeros = np.delete(xk1_nonzeros, 0)
#         print ('New Basic variable Index are: ', basicColIndex)
#         print ('New Basic solution is: ', xk1)#[:,basic])

        i+=1
    
Cn_hat = linearOptimization(A, b, C, X, basicColIndex=basicVar)
print ('THe solution is: ', Cn_hat)



BBBBBBBBBB: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
bbbbbbbbbb: 
 [2 7 3]
NNNNNNNNNN: 
 [[-2  1]
 [-1  2]
 [ 1  0]]
XbXbXbXbXb: 
 [['x3' 'x4' 'x5']]
XnXnXnXnXn: 
 [['x1' 'x2']]
CbCbCbCbCb = C[:,basicColIndex].flatten(): 
 [0 0 0]
CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() 
 [-1 -2]
yyyyyyyyyy: 
 [ 0.  0.  0.]
Cn_hatCn_hat: 
 [-1. -2.]
###########################  [ 2.  7.  3.]
Not yet optimal
indiceindiceindice:  1
atatatatatatatatatat:  [[1]
 [2]
 [0]]
b_hatb_hatb_hatb_hat:  [[ 2.]
 [ 7.]
 [ 3.]]
at_hatat_hatat_hatat_hat:  [[ 1.]
 [ 2.]
 [ 0.]]
b_ab_ab_ab_ab_ab_ab_ab_a:  [ 2.   3.5  inf]
indice2indice2indice2i:  0
epsilonepsilonepsilon:  3.5
vertex1vertex1vertex1:  [[-1.5]
 [ 0. ]
 [ 3. ]]
ververtex2vertex2vertex2:  [[ 0. ]
 [ 3.5]
 [ 0. ]]
xk1_tempxk1_tempxk1_tempxk1_temp: 
 [[-1.5]
 [ 0. ]
 [ 3. ]
 [ 0. ]
 [ 3.5]
 [ 0. ]]
indice3indice3:  [0 2 4]
X_copyX_copyX_copy:  [['x3' 'x4' 'x5' 'x1' 'x2']]
['x3' 'x5' 'x2'] ['x1' 'x2' 'x3' 'x4' 'x5']


BBBBBBBB

/Users/sam/App-Setup/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:64: RuntimeWarning: divide by zero encountered in true_divide


## Question 2.2 (i)   --> Doubt:

In [124]:
A = np.array([[2,3,2,1,1,0], [3,2,4,-1,0,1]])  # The input matrix in standard form
b = np.array([38,55]) # The response variables
C = np.array([-5,-7,-12,1,0,0]).reshape(1,A.shape[1]) # The function to minimize
X = np.array(['x'+str(i) for i in np.arange(1,A.shape[1]+1)]).reshape(1,6)
basicVar = [,5]

def linearOptimization(A, b, C, X, basicColIndex):
    i = 0
    X_copy = X
    while i<10:
        Xb = X[:,basicColIndex]
        Xn = X[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        X_copy = np.column_stack((Xb, Xn))
        
        # xVar = []
        B = A[:,basicColIndex]   # chose a square matrix
        N = A[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        Cb = C[:,basicColIndex].flatten()
        Cn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten()
        y = np.dot(np.linalg.inv(B).T, Cb)
        Cn_hat = Cn - np.dot(N.T,y)
        print ('')
        print ('')
        print ('BBBBBBBBBB: \n', B)
        print ('bbbbbbbbbb: \n', b)
        print ('NNNNNNNNNN: \n', N)
        print ('XbXbXbXbXb: \n', Xb)
        print ('XnXnXnXnXn: \n', Xn)
        print ('CbCbCbCbCb = C[:,basicColIndex].flatten(): \n', Cb)
        print ('CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() \n', Cn)
        print ('yyyyyyyyyy: \n', y)
        print ('Cn_hatCn_hat: \n', Cn_hat)
        # Check if all elements in Cn_hat >= 0, if so then, we have our optimal vertex which is B
        
        feasibleSol = np.dot(np.linalg.inv(B), b)
        print ('########################### ',feasibleSol)
        if any(Cn_hat<0):
            print ('Not yet optimal')
        elif min(feasibleSol) < 0:
            print ('Not yet optimal: Since feasible solution is < 0' )
            pass
        else:
            print ('')
            print ('')
            print ('BASIC COLUMNS: ', Xb)
            print ('NULL COLUMNS: ', Xn)

            return feasibleSol

        # Select the most negative value in the array
        print ('Cn_hatCn_hatCn_hatCn_hatCn_hatCn_hatCn_hatCn_hatCn_hatCn_hatCn_hatCn_hat', Cn_hat)
        Cn_hat = Cn_hat[0:2]
        indice = np.where(Cn_hat == Cn_hat.min())[0][0]
        ct_hat = Cn_hat[indice]
        print ('indiceindiceindice: ', indice)
        
        # Get the corresponding at
        at = N[:,indice].reshape(A.shape[0], 1)
        print ('atatatatatatatatatat: ', at)
        b_hat = np.dot(np.linalg.inv(B), b).reshape(A.shape[0], 1)
        print ('b_hatb_hatb_hatb_hat: ', b_hat)
        at_hat = np.dot(np.linalg.inv(B), at)
        print ('at_hatat_hatat_hatat_hat: ', at_hat)
        
        # Find the min epsilon
        b_a = (b_hat/at_hat).flatten()
        print ('b_ab_ab_ab_ab_ab_ab_ab_a: ', b_a)
        indice2 = np.where(b_a == b_a.min())[0][0]
        print ('indice2indice2indice2i: ', indice2)
        epsilon = b_a[indice]
        print ('epsilonepsilonepsilon: ', epsilon)

        # Vertex points 1 
        vertex1 = b_hat - epsilon*at_hat
        print ('vertex1vertex1vertex1: ', vertex1)
        # Vertex points 2:
        vertex2 = np.zeros(at_hat.shape)
        vertex2[indice] = epsilon
        print ('ververtex2vertex2vertex2: ', vertex2)

        # New Vertex solution
        xk1_temp = np.vstack((vertex1, vertex2))
        print ('xk1_tempxk1_tempxk1_tempxk1_temp: \n', xk1_temp)
        
        # Now we select the 
        indice3 = np.where(xk1_temp.flatten() != 0)[0]
        print ('indice3indice3: ', indice3)
        print ('X_copyX_copyX_copy: ', X_copy)
        X_new = X_copy.flatten()[indice3]
        print (X_new, X.flatten())
        basicColIndex = np.searchsorted(X.flatten(),X_new)
        
#         xk1_nonzeros = [vals for vals in xk1_temp if vals!=0]#np.zeros(A.shape[1])
#         xk1 = np.zeros(A.shape[1]) 
#         for basic_solution_column in basicColIndex:
#             xk1[basic_solution_column] = xk1_nonzeros[0]
#             xk1_nonzeros = np.delete(xk1_nonzeros, 0)
#         print ('New Basic variable Index are: ', basicColIndex)
#         print ('New Basic solution is: ', xk1)#[:,basic])

        i+=1
    
Cn_hat = linearOptimization(A, b, C, X, basicColIndex=basicVar)
print ('THe solution is: ', Cn_hat)



BBBBBBBBBB: 
 [[ 2  1]
 [ 4 -1]]
bbbbbbbbbb: 
 [38 55]
NNNNNNNNNN: 
 [[2 3 1 0]
 [3 2 0 1]]
XbXbXbXbXb: 
 [['x3' 'x4']]
XnXnXnXnXn: 
 [['x1' 'x2' 'x5' 'x6']]
CbCbCbCbCb = C[:,basicColIndex].flatten(): 
 [-12   1]
CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() 
 [-5 -7  0  0]
yyyyyyyyyy: 
 [-1.33333333 -2.33333333]
Cn_hatCn_hat: 
 [ 4.66666667  1.66666667  1.33333333  2.33333333]
###########################  [ 15.5   7. ]


BASIC COLUMNS:  [['x3' 'x4']]
NULL COLUMNS:  [['x1' 'x2' 'x5' 'x6']]
THe solution is:  [ 15.5   7. ]


## Question 2.2 (ii)

In [82]:
A = np.array([[4,5,2,1,1,0], [3,4,-1,1,0,1]])  # The input matrix in standard form
b = np.array([20,30]) # The response variables
C = np.array([-5,-3,-2,0,0,0]).reshape(1,A.shape[1]) # The function to minimize
X = np.array(['x'+str(i) for i in np.arange(1,A.shape[1]+1)]).reshape(1,6)
basicVar = [4,5]

def linearOptimization(A, b, C, X, basicColIndex):
    i = 0
    X_copy = X
    while i<10:
        Xb = X[:,basicColIndex]
        Xn = X[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        X_copy = np.column_stack((Xb, Xn))
        
        # xVar = []
        B = A[:,basicColIndex]   # chose a square matrix
        N = A[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        Cb = C[:,basicColIndex].flatten()
        Cn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten()
        y = np.dot(np.linalg.inv(B).T, Cb)
        Cn_hat = Cn - np.dot(N.T,y)
        print ('')
        print ('')
        print ('BBBBBBBBBB: \n', B)
        print ('bbbbbbbbbb: \n', b)
        print ('NNNNNNNNNN: \n', N)
        print ('XbXbXbXbXb: \n', Xb)
        print ('XnXnXnXnXn: \n', Xn)
        print ('CbCbCbCbCb = C[:,basicColIndex].flatten(): \n', Cb)
        print ('CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() \n', Cn)
        print ('yyyyyyyyyy: \n', y)
        print ('Cn_hatCn_hat: \n', Cn_hat)
        # Check if all elements in Cn_hat >= 0, if so then, we have our optimal vertex which is B
        
        feasibleSol = np.dot(np.linalg.inv(B), b)
        print ('########################### ',feasibleSol)
        if any(Cn_hat<0):
            print ('Not yet optimal')
        elif min(feasibleSol) < 0:
            print ('Not yet optimal: Since feasible solution is < 0' )
            pass
        else:
            print ('')
            print ('')
            print ('BASIC COLUMNS: ', Xb)
            print ('NULL COLUMNS: ', Xn)

            return feasibleSol

        # Select the most negative value in the array 
        indice = np.where(Cn_hat == Cn_hat.min())[0][0]
        ct_hat = Cn_hat[indice]
        print ('indiceindiceindice: ', indice)
        
        # Get the corresponding at
        at = N[:,indice].reshape(A.shape[0], 1)
        print ('atatatatatatatatatat: ', at)
        b_hat = np.dot(np.linalg.inv(B), b).reshape(A.shape[0], 1)
        print ('b_hatb_hatb_hatb_hat: ', b_hat)
        at_hat = np.dot(np.linalg.inv(B), at)
        print ('at_hatat_hatat_hatat_hat: ', at_hat)
        
        # Find the min epsilon
        b_a = (b_hat/at_hat).flatten()
        print ('b_ab_ab_ab_ab_ab_ab_ab_a: ', b_a)
        indice2 = np.where(b_a == b_a.min())[0][0]
        print ('indice2indice2indice2i: ', indice2)
        epsilon = b_a[indice2]
        print ('epsilonepsilonepsilon: ', epsilon)

        # Vertex points 1 
        vertex1 = b_hat - epsilon*at_hat
        print ('vertex1vertex1vertex1: ', vertex1)
        # Vertex points 2:
        vertex2 = np.zeros(at_hat.shape)
        vertex2[indice2] = epsilon
        print ('ververtex2vertex2vertex2: ', vertex2)

        # New Vertex solution
        xk1_temp = np.vstack((vertex1, vertex2))
        print ('xk1_tempxk1_tempxk1_tempxk1_temp: \n', xk1_temp)
        
        # Now we select the 
        indice3 = np.where(xk1_temp.flatten() != 0)[0]
        print ('indice3indice3: ', indice3)
        print ('X_copyX_copyX_copy: ', X_copy)
        X_new = X_copy.flatten()[indice3]
        print (X_new, X.flatten())
        basicColIndex = np.searchsorted(X.flatten(),X_new)
        
#         xk1_nonzeros = [vals for vals in xk1_temp if vals!=0]#np.zeros(A.shape[1])
#         xk1 = np.zeros(A.shape[1]) 
#         for basic_solution_column in basicColIndex:
#             xk1[basic_solution_column] = xk1_nonzeros[0]
#             xk1_nonzeros = np.delete(xk1_nonzeros, 0)
#         print ('New Basic variable Index are: ', basicColIndex)
#         print ('New Basic solution is: ', xk1)#[:,basic])

        i+=1
    
Cn_hat = linearOptimization(A, b, C, X, basicColIndex=basicVar)
print ('THe solution is: ', Cn_hat)



BBBBBBBBBB: 
 [[1 0]
 [0 1]]
bbbbbbbbbb: 
 [20 30]
NNNNNNNNNN: 
 [[ 4  5  2  1]
 [ 3  4 -1  1]]
XbXbXbXbXb: 
 [['x5' 'x6']]
XnXnXnXnXn: 
 [['x1' 'x2' 'x3' 'x4']]
CbCbCbCbCb = C[:,basicColIndex].flatten(): 
 [0 0]
CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() 
 [-5 -3 -2  0]
yyyyyyyyyy: 
 [ 0.  0.]
Cn_hatCn_hat: 
 [-5. -3. -2.  0.]
###########################  [ 20.  30.]
Not yet optimal
indiceindiceindice:  0
atatatatatatatatatat:  [[4]
 [3]]
b_hatb_hatb_hatb_hat:  [[ 20.]
 [ 30.]]
at_hatat_hatat_hatat_hat:  [[ 4.]
 [ 3.]]
b_ab_ab_ab_ab_ab_ab_ab_a:  [  5.  10.]
indice2indice2indice2i:  0
epsilonepsilonepsilon:  5.0
vertex1vertex1vertex1:  [[  0.]
 [ 15.]]
ververtex2vertex2vertex2:  [[ 5.]
 [ 0.]]
xk1_tempxk1_tempxk1_tempxk1_temp: 
 [[  0.]
 [ 15.]
 [  5.]
 [  0.]]
indice3indice3:  [1 2]
X_copyX_copyX_copy:  [['x5' 'x6' 'x1' 'x2' 'x3' 'x4']]
['x6' 'x1'] ['x1' 'x2' 'x3' 'x4' 'x5' 'x6']


BBBBBBBBBB: 
 [[0 4]
 [1 3]]
bbbbbbbbbb: 
 [20 30]
NNNNNNNNN

## Question 2.2 (iii)

In [90]:
A = np.array([[-5,2,1,0], [-3,1,0,1]])  # The input matrix in standard form
b = np.array([30,12]) # The response variables
C = np.array([3,9,0,0]).reshape(1,A.shape[1]) # The function to minimize
X = np.array(['x'+str(i) for i in np.arange(1,A.shape[1]+1)]).reshape(1,4)
basicVar = [2,3]

def linearOptimization(A, b, C, X, basicColIndex):
    i = 0
    X_copy = X
    while i<10:
        Xb = X[:,basicColIndex]
        Xn = X[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        X_copy = np.column_stack((Xb, Xn))
        
        # xVar = []
        B = A[:,basicColIndex]   # chose a square matrix
        N = A[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
        Cb = C[:,basicColIndex].flatten()
        Cn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten()
        y = np.dot(np.linalg.inv(B).T, Cb)
        Cn_hat = Cn - np.dot(N.T,y)
        print ('')
        print ('')
        print ('BBBBBBBBBB: \n', B)
        print ('bbbbbbbbbb: \n', b)
        print ('NNNNNNNNNN: \n', N)
        print ('XbXbXbXbXb: \n', Xb)
        print ('XnXnXnXnXn: \n', Xn)
        print ('CbCbCbCbCb = C[:,basicColIndex].flatten(): \n', Cb)
        print ('CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() \n', Cn)
        print ('yyyyyyyyyy: \n', y)
        print ('Cn_hatCn_hat: \n', Cn_hat)
        # Check if all elements in Cn_hat >= 0, if so then, we have our optimal vertex which is B
        
        feasibleSol = np.dot(np.linalg.inv(B), b)
        print ('########################### ',feasibleSol)
        if any(Cn_hat<0):
            print ('Not yet optimal')
        elif min(feasibleSol) < 0:
            print ('Not yet optimal: Since feasible solution is < 0' )
            pass
        else:
            print ('')
            print ('')
            print ('BASIC COLUMNS: ', Xb)
            print ('NULL COLUMNS: ', Xn)

            return feasibleSol

        # Select the most negative value in the array 
        indice = np.where(Cn_hat == Cn_hat.min())[0][0]
        ct_hat = Cn_hat[indice]
        print ('indiceindiceindice: ', indice)
        
        # Get the corresponding at
        at = N[:,indice].reshape(A.shape[0], 1)
        print ('atatatatatatatatatat: ', at)
        b_hat = np.dot(np.linalg.inv(B), b).reshape(A.shape[0], 1)
        print ('b_hatb_hatb_hatb_hat: ', b_hat)
        at_hat = np.dot(np.linalg.inv(B), at)
        print ('at_hatat_hatat_hatat_hat: ', at_hat)
        
        # Find the min epsilon
        b_a = (b_hat/at_hat).flatten()
        print ('b_ab_ab_ab_ab_ab_ab_ab_a: ', b_a)
        indice2 = np.where(b_a == b_a.min())[0][0]
        print ('indice2indice2indice2i: ', indice2)
        epsilon = b_a[indice2]
        print ('epsilonepsilonepsilon: ', epsilon)

        # Vertex points 1 
        vertex1 = b_hat - epsilon*at_hat
        print ('vertex1vertex1vertex1: ', vertex1)
        # Vertex points 2:
        vertex2 = np.zeros(at_hat.shape)
        vertex2[indice2] = epsilon
        print ('ververtex2vertex2vertex2: ', vertex2)

        # New Vertex solution
        xk1_temp = np.vstack((vertex1, vertex2))
        print ('xk1_tempxk1_tempxk1_tempxk1_temp: \n', xk1_temp)
        
        # Now we select the 
        indice3 = np.where(xk1_temp.flatten() != 0)[0]
        print ('indice3indice3: ', indice3)
        print ('X_copyX_copyX_copy: ', X_copy)
        X_new = X_copy.flatten()[indice3]
        print (X_new, X.flatten())
        basicColIndex = np.searchsorted(X.flatten(),X_new)
        
#         xk1_nonzeros = [vals for vals in xk1_temp if vals!=0]#np.zeros(A.shape[1])
#         xk1 = np.zeros(A.shape[1]) 
#         for basic_solution_column in basicColIndex:
#             xk1[basic_solution_column] = xk1_nonzeros[0]
#             xk1_nonzeros = np.delete(xk1_nonzeros, 0)
#         print ('New Basic variable Index are: ', basicColIndex)
#         print ('New Basic solution is: ', xk1)#[:,basic])

        i+=1
    
Cn_hat = linearOptimization(A, b, C, X, basicColIndex=basicVar)
print ('THe solution is: ', Cn_hat)



BBBBBBBBBB: 
 [[1 0]
 [0 1]]
bbbbbbbbbb: 
 [30 12]
NNNNNNNNNN: 
 [[-5  2]
 [-3  1]]
XbXbXbXbXb: 
 [['x3' 'x4']]
XnXnXnXnXn: 
 [['x1' 'x2']]
CbCbCbCbCb = C[:,basicColIndex].flatten(): 
 [0 0]
CnCnCnCnCn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten() 
 [3 9]
yyyyyyyyyy: 
 [ 0.  0.]
Cn_hatCn_hat: 
 [ 3.  9.]
###########################  [ 30.  12.]


BASIC COLUMNS:  [['x3' 'x4']]
NULL COLUMNS:  [['x1' 'x2']]
THe solution is:  [ 30.  12.]


In [136]:
A = np.array([[2,3,2,1,1,0], [3,2,4,-1,0,1]])  # The input matrix in standard form
b = np.array([38,55]) # The response variables
C = np.array([-5,-7,-12,1,0,0]).reshape(1,A.shape[1]) # The function to minimize
X = np.array(['x'+str(i) for i in np.arange(1,A.shape[1]+1)]).reshape(1,6)



basicColIndex = [1,5]
B = A[:,basicColIndex]   # chose a square matrix
print ('B ',B)
N = A[:,[i for i in range(A.shape[1]) if i not in basicColIndex]]
print ('N ', N)
Cb = C[:,basicColIndex].flatten()
print ('Cb ', Cb)
Cn = C[:,[i for i in range(A.shape[1]) if i not in basicColIndex]].flatten()
print ('Cn', Cn)
y = np.dot(np.linalg.inv(B).T, Cb)
print ('Y ', y)
Cn_hat = Cn - np.dot(N.T,y)
print ('Cn_hat ', Cn_hat)
        
ct_hat = Cn_hat[0]

at = N[:,0].reshape(A.shape[0], 1)
print ('at ', at)
b_hat = np.dot(np.linalg.inv(B), b).reshape(A.shape[0], 1)
print ('b_hat ', b_hat)
at_hat = np.dot(np.linalg.inv(B), at)
print ('at_hat ', at_hat)
b_a = (b_hat/at_hat).flatten()
print ('b_a ', b_a)



B  [[3 0]
 [2 1]]
N  [[ 2  2  1  1]
 [ 3  4 -1  0]]
Cb  [-7  0]
Cn [ -5 -12   1   0]
Y  [-2.33333333  0.        ]
Cn_hat  [-0.33333333 -7.33333333  3.33333333  2.33333333]
at  [[2]
 [3]]
b_hat  [[ 12.66666667]
 [ 29.66666667]]
at_hat  [[ 0.66666667]
 [ 1.66666667]]
b_a  [ 19.   17.8]


In [137]:
B = [[3,0],[2,1]]
b = np.array([38,55])

np.dot(np.linalg.inv(B), b)

array([ 12.66666667,  29.66666667])

In [138]:
B = [[3,2],[2,4]]
b = np.array([38,55])

np.dot(np.linalg.inv(B), b)

array([  5.25 ,  11.125])

In [ ]:
x = np.array([0,0,5,10,5])