In [2]:
# Ssteepest descent for a funtion

from __future__ import division
import numpy as np
from sympy import *

## Steepest Descent for Non Quadratic Function:

In [3]:
x1 = Symbol('x1')
x2 = Symbol('x2')
f = 4*pow(x1,2) + 2*pow(x2,2) + 4*x1*x2 - 3*x1

deriv_f_x1 = f.diff(x1)
deriv_f_x2 = f.diff(x2)
print (f)
print (deriv_f_x1)
print (deriv_f_x2)

4*x1**2 + 4*x1*x2 - 3*x1 + 2*x2**2
8*x1 + 4*x2 - 3
4*x1 + 4*x2


In [6]:
x_step = np.array([2,2])
# print (deriv_f_x1)
# print (deriv_f_x2)
iteration = 0
numSteps = 3
while (iteration<numSteps):
    # Solve for gradient
    deriv_f_x1_s = deriv_f_x1.subs(x1,x_step[0]).subs(x2,x_step[1])
    deriv_f_x2_s = deriv_f_x2.subs(x1,x_step[0]).subs(x2,x_step[1])

    gradient_subs = np.array([deriv_f_x1_s, deriv_f_x2_s], dtype='float32')
    print ('Gradient of function at xstep at iteration %s is: '%(iteration), gradient_subs)
    print ('Gradient Norm is: ', np.linalg.norm(gradient_subs))

    f_x_stepNext = x_step - np.array([Symbol('alpha')*deriv_f_x1_s, Symbol('alpha')*deriv_f_x2_s])
    print ("f_x_stepNext at current state is: ",  f_x_stepNext)
    f_x_stepNext_subs = np.array([deriv_f_x1.subs(x1, f_x_stepNext[0]).subs(x2, f_x_stepNext[1]), 
                      deriv_f_x2.subs(x1, f_x_stepNext[0]).subs(x2, f_x_stepNext[1])])
    print ("f_x_stepNext_subs for current state is : ", f_x_stepNext_subs)
    f_x_stepNext_subs = np.dot(f_x_stepNext_subs, gradient_subs)

    alpha = solve(str(f_x_stepNext_subs))
    print ('The new alpha at Iteration %s is: '%(iteration), alpha)   

    x_stepNext = x_step - (alpha*gradient_subs)
    print ('The next step at Iteration %s is: '%(iteration), x_stepNext)
    
    x_step = x_stepNext
    
    iteration += 1
    
    print('')

Gradient of function at xstep at iteration 0 is:  [ 21.  16.]
Gradient Norm is:  26.4008
f_x_stepNext at current state is:  [-21.0*alpha + 2 -16.0*alpha + 2]
f_x_stepNext_subs for current state is :  [-232.0*alpha + 21 -148.0*alpha + 16]
The new alpha at Iteration 0 is:  [0.0962707182320442]
The next step at Iteration 0 is:  [-0.0216850828729283 0.459668508287293]

Gradient of function at xstep at iteration 1 is:  [-1.33480668  1.75193369]
Gradient Norm is:  2.20249
f_x_stepNext at current state is:  [1.33480662983425*alpha - 0.0216850828729283
 -1.75193370165746*alpha + 0.459668508287293]
f_x_stepNext_subs for current state is :  [3.6707182320442*alpha - 1.33480662983425
 -1.66850828729282*alpha + 1.75193370165746]
The new alpha at Iteration 1 is:  [0.620106754734336]
The next step at Iteration 1 is:  [0.806037556080837 -0.626717409137971]

Gradient of function at xstep at iteration 2 is:  [ 0.94143081  0.71728057]
Gradient Norm is:  1.18355
f_x_stepNext at current state is:  [-0.9414

## Steepest descent for Quadratic functions

In [2]:
import numpy as np
Q1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
Q2 = np.array([[1,0,0],[0,10,0],[0,0,100]])
Q3 = np.array([[1,0,0],[0,100,0],[0,0,10000]])
Q4 = np.array([[1,0,0],[0,1000,0],[0,0,1000000]])

Q5 = np.array([[1,0,0],[0,5,0],[0,0,25]])

Q = Q4
c = np.array([1,1,1])
xk = np.array([0,0,0])

iteration = 0
num_steps = 4
while iteration<=num_steps:
    pk = -1 * (np.dot(Q, xk) - c)
    gradient_k = np.dot(Q, xk) - c
    gradient_norm = np.linalg.norm(gradient_k)
    numerator = np.dot(-gradient_k,pk)
    denominator = np.dot(np.dot(np.transpose(pk),Q), pk)
    alpha = numerator/denominator
    x_new = xk - alpha*gradient_k
    xk  = x_new
    print ('Gradient direction : ', pk, pk.shape)
    print ('Gradient : ', gradient_k, gradient_k.shape)
    print ('Gradient Norm : ',gradient_norm)
    print ('Numerator : ', numerator)
    print ('Denominator : ', denominator)
    print ('The value of aplha : ', alpha)
    print ('The new x a step towards minimum is : ', x_new)
    iteration += 1
    print ('')
# alpha_k = np.dot(-gradient_k,pk)/np.dot(np.dot(np.transpose(pk),Q), pk)
# print (pk)

Gradient direction :  [1 1 1] (3,)
Gradient :  [-1 -1 -1] (3,)
Gradient Norm :  1.73205080757
Numerator :  3
Denominator :  1001001
The value of aplha :  2.997000003e-06
The new x a step towards minimum is :  [  2.99700000e-06   2.99700000e-06   2.99700000e-06]

Gradient direction :  [ 0.999997  0.997003 -1.997   ] (3,)
Gradient :  [-0.999997 -0.997003  1.997   ] (3,)
Gradient Norm :  2.4458164281
Numerator :  5.98201799998
Denominator :  3989004.02695
The value of aplha :  1.49962696442e-06
The new x a step towards minimum is :  [  4.49662247e-06   4.49213259e-06   2.24495056e-09]

Gradient direction :  [ 0.9999955   0.99550787  0.99775505] (3,)
Gradient :  [-0.9999955  -0.99550787 -0.99775505] (3,)
Gradient Norm :  1.72816146802
Numerator :  2.98654205954
Denominator :  996507.17459
The value of aplha :  2.99701009255e-06
The new x a step towards minimum is :  [  7.49361909e-06   7.47567971e-06   2.99252690e-06]

Gradient direction :  [ 0.99999251  0.99252432 -1.9925269 ] (3,)
Gradie

### Assignment 4:

In [24]:
# Question 3.3:

x1 = Symbol('x1')
x2 = Symbol('x2')

f = 5*pow(x1,4) + 6*pow(x2,4) - 6*pow(x1,2) + 2*x1*x2 + 5*pow(x2,2) + 15*x1 - 7*x2 + 13

deriv_f_x1 = f.diff(x1)
deriv_f_x2 = f.diff(x2)
deriv_f_x1x1 = deriv_f_x1.diff(x1)
deriv_f_x2x2 = deriv_f_x2.diff(x2)
deriv_f_x1x2 = deriv_f_x1.diff(x2)
deriv_f_x2x1 = deriv_f_x2.diff(x1)

print (deriv_f_x1)
print (deriv_f_x2)
print (deriv_f_x1x1)
print (deriv_f_x2x2)
print (deriv_f_x1x2)
print (deriv_f_x2x1)

valx1 = 1
valx2 = 1
i = 1
print('')
while (i<=5):
    order1 = np.array([deriv_f_x1.subs(x1,valx1).subs(x2,valx2),deriv_f_x2.subs(x1,valx1).subs(x2,valx2)])
    order2 =  np.array([[deriv_f_x1x1.subs(x1,valx1).subs(x2,valx2), deriv_f_x1x2],
                        [deriv_f_x2x1, deriv_f_x2x2.subs(x1,valx1).subs(x2,valx2)] ])
    print(order1)
    print (order2)
    order2_inv = np.linalg.inv(np.array(order2, dtype=float))
    alpha_pk = np.dot(order2_inv,order1)
    print ('pkpkpk', alpha_pk)
    xk_1 = np.array([valx1,valx2], dtype=float) - alpha_pk
    print (xk_1)
    valx1 = xk_1[0]
    valx2 = xk_1[1]
    
    i+=1
    print ('')
    print ('')

20*x1**3 - 12*x1 + 2*x2 + 15
2*x1 + 24*x2**3 + 10*x2 - 7
60*x1**2 - 12
72*x2**2 + 10
2
2

[25 29]
[[48 2]
 [2 82]]
pkpkpk [0.506612410986775 0.341302136317396]
[0.493387589013225 0.658697863682604]


[12.7988644313582 7.43289917307754]
[[2.60587877953697 2]
 [2 41.2395670446419]]
pkpkpk [4.95773720083601 -0.0601988674106860]
[-4.46434961182279 0.718896731093290]


[-1709.51703991113 0.177103863534757]
[[1183.82504739494 2]
 [2 47.2105007183165]]
pkpkpk [-1.44417192948819 0.0649314808330726]
[-3.02017768233460 0.653965250260218]


[-498.419335070114 0.211657393374366]
[[535.288393972320 2]
 [2 40.7922794954495]]
pkpkpk [-0.931312990316576 0.0508499010024412]
[-2.08886469201803 0.603115349257777]


[-141.016586271334 0.118593960283523]
[[249.801342093574 2]
 [2 36.1898649647437]]
pkpkpk [-0.564791063194704 0.0344896585795196]
[-1.52407362882332 0.568625690678257]




In [ ]:
# i = 0 
# x = 4
# while i<= 20:
#     x = (2/3) * x
#     print (x)
#     print (4*pow(x,3))
#     print ('')

2.6666666666666665
75.85185185185183

1.7777777777777777
22.474622770919062

1.1851851851851851
6.659147487679722

0.7901234567901234
1.973080737090288

0.5267489711934156
0.5846165146934186

0.35116598079561034
0.17321970805730916

0.23411065386374022
0.051324357942906414

0.15607376924249347
0.015207217168268563

0.10404917949499565
0.004505842123931426

0.06936611966333042
0.0013350643330167183

0.046244079775553615
0.0003955746171901388

0.03082938651703574
0.00011720729398226332

0.02055292434469049
3.472808710585578e-05

0.013701949563126994
1.0289803586920233e-05

0.009134633042084662
3.0488306924208084e-06

0.0060897553613897745
9.033572421987581e-07

0.004059836907593183
2.6766140509592825e-07

0.002706557938395455
7.930708299138614e-08

0.0018043719589303034
2.349839496041071e-08

0.001202914639286869
6.962487395677247e-09

0.0008019430928579126
2.062959228348814e-09

0.0005346287285719417
6.112471787700188e-10

0.00035641915238129445
1.8111027519111666e-10

0.000237612768254

1.06855036397e-313

1.9929071992749453e-105
3.1660751535e-314

1.3286047995166302e-105
9.38096341e-315

8.857365330110868e-106
2.77954471e-315

5.904910220073912e-106
8.23568796e-316

3.9366068133826077e-106
2.44020386e-316

2.6244045422550715e-106
7.2302337e-317

1.7496030281700475e-106
2.1422924e-317

1.1664020187800316e-106
6.34754e-318

7.776013458533544e-107
1.88075e-318

5.184008972355695e-107
5.57267e-319

3.4560059815704635e-107
1.65117e-319

2.3040039877136422e-107
4.893e-320

1.5360026584757614e-107
1.4486e-320

1.0240017723171743e-107
4.29e-321

6.826678482114495e-108
1.265e-321

4.55111898807633e-108
3.75e-322

3.0340793253842197e-108
1.2e-322

2.0227195502561463e-108
4e-323

1.3484797001707642e-108
0.0

8.989864667805094e-109
0.0

5.993243111870062e-109
0.0

3.9954954079133745e-109
0.0

2.663663605275583e-109
0.0

1.7757757368503887e-109
0.0

1.1838504912335923e-109
0.0

7.892336608223948e-110
0.0

5.261557738815965e-110
0.0

3.507705159210643e-110
0.0

2.3384701061404286e


1.011236104400746e-241
0.0

5e-324
0.0

5e-324