In [2]:
from __future__ import division

import numpy as np

In [88]:
# 3.3:
x = 19
y = 59
z = 4


x = [1,1]
i = 0
while i <10:
    x1 = x[0]
    x2 = x[1]
    N1 = 20*pow(x1,3) - (12*x1) + (2*x2) + 15
    N2 = 24*pow(x2,3) + (2*x1) + (10*x2) - 7
    deriv1= np.array([N1,N2])
    deriv1Norm = np.linalg.norm(deriv1)
    deriv2 = np.array([[60*pow(x1,2) - 12 , 2],
                       [2, 72*pow(x2,2)+10]])

    pk = np.dot(np.linalg.inv(deriv2),  deriv1)

    x = x - pk
    print ('###############')
    print ('deriv1 ',deriv1)
    print ('deriv2 ',deriv2)
    print ('pk ', pk)
    print ('X ', x)
    print ('deriv1Norm ',deriv1Norm)
    print ('')
    print ('')
    i+=1

###############
deriv1  [25 29]
deriv2  [[48  2]
 [ 2 82]]
pk  [ 0.50661241  0.34130214]
X  [ 0.49338759  0.65869786]
deriv1Norm  38.2883794382


###############
deriv1  [ 12.79886443   7.43289917]
deriv2  [[  2.60587878   2.        ]
 [  2.          41.23956704]]
pk  [ 4.9577372  -0.06019887]
X  [-4.46434961  0.71889673]
deriv1Norm  14.8006392041


###############
deriv1  [ -1.70951704e+03   1.77103864e-01]
deriv2  [[ 1183.82504739     2.        ]
 [    2.            47.21050072]]
pk  [-1.44417193  0.06493148]
X  [-3.02017768  0.65396525]
deriv1Norm  1709.51704908


###############
deriv1  [ -4.98419335e+02   2.11657393e-01]
deriv2  [[ 535.28839397    2.        ]
 [   2.           40.7922795 ]]
pk  [-0.93131299  0.0508499 ]
X  [-2.08886469  0.60311535]
deriv1Norm  498.419380011


###############
deriv1  [ -1.41016586e+02   1.18593960e-01]
deriv2  [[ 249.80134209    2.        ]
 [   2.           36.18986496]]
pk  [-0.56479106  0.03448966]
X  [-1.52407363  0.56862569]
deriv1Norm  141.01

In [5]:
# Question 

Q = np.array([[5,2,1],[2,7,3],[1,3,9]])
C = np.array([-9,0,-8]).reshape((3,1))
xk = np.array([0,0,0]).reshape((3,1))
Bk = np.array([[1,0,0],[0,1,0],[0,0,1]])

# Q = np.array([[2,0,0],[0,3,0],[0,0,4]])
# C = np.array([-8,-9,-8]).reshape((3,1))
# xk = np.array([0,0,0]).reshape((3,1))
# Bk = np.array([[1,0,0],[0,1,0],[0,0,1]])
i = 0
while i <= 5:
    deriv1_xk = np.dot(Q,xk) - C
    print ('0000000000000 ', Bk)
    print ('9090909090909 ', deriv1_xk)
    pk = -1 * np.dot(np.linalg.inv(Bk),deriv1_xk)
    print ('1212121212121 ', pk)
    print ('2323232323232 ', Q)
    print ('3434343434344 ', pk)
    alpha = -1 * (np.dot(np.transpose(pk), deriv1_xk) / np.dot(np.dot(np.transpose(pk), Q), pk))
    print (np.dot(np.dot(np.transpose(pk), Q), pk))
    xk1 = xk + alpha*pk#deriv1_xk
    deriv1_xk_norm = np.linalg.norm(deriv1_xk)


    # Updating Parameters
    # Finding approximated Hessian Bk and deltaBk- a small change
    deriv1_xk1 =  np.dot(Q,xk1) - C
    Sk = xk1 - xk
    Yk = deriv1_xk1 - deriv1_xk
    numerator = Yk - np.dot(Bk, Sk)
    deltaBk = np.dot(numerator, np.transpose(numerator))/np.dot(np.transpose(numerator),Sk)
    Bk1 = Bk + deltaBk


    # print (deriv1_xk1.shape,Sk.shape, Yk.shape,numerator.shape, denominator.shape, w.shape, c.shape)
    print ('')
    print ('xk:\n',xk)
    print ('')
    print ('deriv1_xk: \n', deriv1_xk)
    print ('')
    print ('gradient_norm: \n', deriv1_xk_norm)
    print ('')
    print ('pk: \n',pk)
    print ('')
    print ('alpha:\n', alpha)
    print ('')
    print ('xk1:\n',xk1)
    print ('')
    print ('deriv1_xk1:\n ',deriv1_xk1)
    print ('')
    print ('Sk:\n ', Sk)
    print ('')
    print ('Yk: \n', Yk)
    print ('')
    print ('deltaBk: \n', deltaBk)
    print ('')
    print ('Bk1: \n', Bk1)
    print ('')
    print ('#####################################')
    i+=1
    
    xk = xk1
    Bk = Bk1
    # deltaBk

# deltaBk = c
# Bk_1 = Bk + deltaBk

# deltaBk = np.dot(W,np.transpose(W))

0000000000000  [[1 0 0]
 [0 1 0]
 [0 0 1]]
9090909090909  [[9]
 [0]
 [8]]
1212121212121  [[-9.]
 [-0.]
 [-8.]]
2323232323232  [[5 2 1]
 [2 7 3]
 [1 3 9]]
3434343434344  [[-9.]
 [-0.]
 [-8.]]
[[ 1125.]]

xk:
 [[0]
 [0]
 [0]]

deriv1_xk: 
 [[9]
 [0]
 [8]]

gradient_norm: 
 12.0415945788

pk: 
 [[-9.]
 [-0.]
 [-8.]]

alpha:
 [[ 0.12888889]]

xk1:
 [[-1.16      ]
 [ 0.        ]
 [-1.03111111]]

deriv1_xk1:
  [[ 2.16888889]
 [-5.41333333]
 [-2.44      ]]

Sk:
  [[-1.16      ]
 [ 0.        ]
 [-1.03111111]]

Yk: 
 [[ -6.83111111]
 [ -5.41333333]
 [-10.44      ]]

deltaBk: 
 [[ 1.9755102   1.88571429  3.27755102]
 [ 1.88571429  1.8         3.12857143]
 [ 3.27755102  3.12857143  5.4377551 ]]

Bk1: 
 [[ 2.9755102   1.88571429  3.27755102]
 [ 1.88571429  2.8         3.12857143]
 [ 3.27755102  3.12857143  6.4377551 ]]

#####################################
0000000000000  [[ 2.9755102   1.88571429  3.27755102]
 [ 1.88571429  2.8         3.12857143]
 [ 3.27755102  3.12857143  6.4377551 ]]
909090909

/Users/sam/App-Setup/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in true_divide


In [7]:
# Question 

# Q = np.array([[2,0,0],[0,3,0],[0,0,4]])
# C = np.array([-8,-9,-8]).reshape((3,1))
# xk = np.array([0,0,0]).reshape((3,1))
# Bk = np.array([[1,0,0],[0,1,0],[0,0,1]])


Q = np.array([[5,2,1],[2,7,3],[1,3,9]])
C = np.array([-9,0,-8]).reshape((3,1))
xk = np.array([0,0,0]).reshape((3,1))
Bk = np.array([[1,0,0],[0,1,0],[0,0,1]])


i = 0
while i <= 5:
    deriv1_xk = np.dot(Q,xk) - C
    pk = -1 * np.dot(np.linalg.inv(Bk),deriv1_xk)
    alpha = -1 * (np.dot(np.transpose(pk), deriv1_xk) / np.dot(np.dot(np.transpose(pk), Q), pk))
    xk1 = xk + alpha*pk#deriv1_xk
    deriv1_xk_norm = np.linalg.norm(deriv1_xk)


    # Updating Parameters
    # Finding approximated Hessian Bk and deltaBk- a small change
    deriv1_xk1 =  np.dot(Q,xk1) - C
    Sk = xk1 - xk
    Yk = deriv1_xk1 - deriv1_xk
#     print (Bk.shape, Sk.shape)
    numerator = np.dot(np.dot(Bk,Sk),np.transpose(np.dot(Bk,Sk)))
    denominator = np.dot(np.transpose(Sk),np.dot(Bk,Sk))
    Bk1 = Bk - (numerator/denominator) + (np.dot(Yk, np.transpose(Yk))/np.dot(np.transpose(Yk), Yk))
# #     Bk1 = Bk + deltaBk


#     # print (deriv1_xk1.shape,Sk.shape, Yk.shape,numerator.shape, denominator.shape, w.shape, c.shape)
    print ('')
    print ('gradient_norm: \n', deriv1_xk_norm)
    print ('')
    print ('xk:\n',xk)
    print ('')
    print ('deriv1_xk: \n', deriv1_xk)
    print ('')
    print ('pk: \n',pk)
    print ('')
    print ('alpha:\n', alpha)
    print ('')
    print ('xk1:\n',xk1)
    print ('')
    print ('deriv1_xk1:\n ',deriv1_xk1)
    print ('')
    print ('Sk:\n ', Sk)
    print ('')
    print ('Yk: \n', Yk)
    print ('')
    print ('Bk1: \n', Bk1)
    print ('')
    print ('#####################################')
    i+=1
    
    xk = xk1
    Bk = Bk1
    # deltaBk

# deltaBk = c
# Bk_1 = Bk + deltaBk

# deltaBk = np.dot(W,np.transpose(W))


gradient_norm: 
 12.0415945788

xk:
 [[0]
 [0]
 [0]]

deriv1_xk: 
 [[9]
 [0]
 [8]]

pk: 
 [[-9.]
 [-0.]
 [-8.]]

alpha:
 [[ 0.12888889]]

xk1:
 [[-1.16      ]
 [ 0.        ]
 [-1.03111111]]

deriv1_xk1:
  [[ 2.16888889]
 [-5.41333333]
 [-2.44      ]]

Sk:
  [[-1.16      ]
 [ 0.        ]
 [-1.03111111]]

Yk: 
 [[ -6.83111111]
 [ -5.41333333]
 [-10.44      ]]

Bk1: 
 [[ 0.69366959  0.19992815 -0.11097601]
 [ 0.19992815  1.15843363  0.30555057]
 [-0.11097601  0.30555057  1.14789678]]

#####################################

gradient_norm: 
 6.3215391156

xk:
 [[-1.16      ]
 [ 0.        ]
 [-1.03111111]]

deriv1_xk: 
 [[ 2.16888889]
 [-5.41333333]
 [-2.44      ]]

pk: 
 [[-4.64928   ]
 [ 5.41333333]
 [ 0.2352079 ]]

alpha:
 [[ 0.18290333]]

xk1:
 [[-2.01036879]
 [ 0.99011668]
 [-0.9880908 ]]

deriv1_xk1:
  [[-0.05970136]
 [-0.0541932 ]
 [ 0.06716403]]

Sk:
  [[-0.85036879]
 [ 0.99011668]
 [ 0.04302031]]

Yk: 
 [[-2.22859025]
 [ 5.35914013]
 [ 2.50716403]]

Bk1: 
 [[ 0.70020501  0.19494543

/Users/sam/App-Setup/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


In [48]:


optString = []
def inputString(inputString, StringCount):
    print (len(inputString)-StringCount)
    for i in range(len(inputString)-StringCount+1):
        optString.append(inputString[i:i+StringCount])
#     optString[i:len(a)]
a = "jabcoijadp"
inputString(a, StringCount =2)
optString = set(optString)
optString

8


{'ab', 'ad', 'bc', 'co', 'dp', 'ij', 'ja', 'oi'}

In [44]:
optString

{'ab', 'bc', 'cp', 'ja'}

In [26]:
a = "ewrw"
for i in range(len(a)-3):
    print (i)

0


In [27]:
set(optString)

{'dfg', 'fgh', 'ghj', 'hjs', 'hsd', 'jhs', 'jjh', 'jjj', 'sdf'}

In [72]:
data = [["a", 22],["b", 45], ["a",55]]
arr1 = []
avgDict = {}
dict1 ={} 
dict2 = {}
for i in data:
    print (i)
    if i[0] in dict1.keys():
        dict1[i[0]] = dict1[i[0]] + i[1]
        dict2[i[0]] = dict2[i[0]] + 1
    else:
        dict1[i[0]] = i[1]
        dict2[i[0]] = 1
        
    for name, score in dict1.items():
        avgDict[name] = score/dict2[name]
    for name, score in avgDict.irtems()
    arr1.append([name, score/dict2[name]])
        

['a', 22]
['b', 45]
['a', 55]


In [66]:
dict1

{'a': 77, 'b': 45}

In [67]:
dict2

{'a': 2, 'b': 1}

In [69]:
avgDict

{'a': 38.5, 'b': 45.0}

In [73]:
arr1

[['a', 22.0], ['a', 22.0], ['b', 45.0], ['a', 38.5], ['b', 45.0]]