In [ ]:
from __future__ import division
import numpy as np

In [11]:
BB = np.array([[2,1,0,0,1],
               [1,1,0,1,0],
               [1,0,1,0,0]])

B = BB[:,[0,3,4]]
b = np.array([[100],[80],[40]])

np.dot(np.linalg.inv(B), b)

array([[ 40.],
       [ 40.],
       [ 20.]])

In [24]:
BB = np.array([[-3,2,1,0],
               [-2,1,0,1]])

B = BB[:,[2,3]]
b = np.array([[30],[12]])

np.dot(np.linalg.inv(B), b)

array([[ 30.],
       [ 12.]])

In [17]:
BB = np.array([[0,2,(30/11)],
               [4,0,(4/11)],
               [1,1,1]])

CC = np.array([[2,3,(30/11)],
               [0,0,(4/11)],
               [1,1,1]])

In [19]:
np.dot(np.linalg.inv(CC), np.array([[1],[1],[1]]))

array([[ 1.25],
       [-3.  ],
       [ 2.75]])